### PR TITLE
feature/remove point filter option

### PR DESCRIPTION
**Pull request by alexp8**
- Create a UserSettings table
- From the Manage Account page, users can interact with their "user settings"
image
image

- When point filter is disabled by both players in queue, when they search for a match, the point filter will be ignored.

### CODE REVIEW

**Comment by GrantBartlett** [comment]
Haven't had a proper look yet but could you make your braces alman style, as majority of the codebase is already this 👍

**Comment by alexp8** [comment]
sure can do  👍

**Comment by GrantBartlett** [comment]
```html
<form method="POST" action="/account/settings">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <input id="disablePointFilter" type="checkbox" name="disabledPointFilter" @if($userSettings->disabledPointFilter) checked @endif />
    <label for="disablePointFilter">Disable Point Filter</label>

    {{-- TODO future functionality will use this value, no need to have users touch this yet
    <input id="enableAnonymous" type="checkbox" name="enableAnonymous"  value="{{ $userSettings->enableAnonymous }}" @if($userSettings->enableAnonymous) checked @endif /> 
    <label for="enableAnonymous"> Enable Anonymity </label>  
    --}}
    
    <div>
        <button type="submit" class="btn btn-primary">Save Settings</button>
    </div>
</form>
```
Just a little change here ^
image

**Comment by alexp8** [comment]
thanks, updated

**Pull request closed without merging**
